Repository omni-us/jsonargparse, pull requests merged in 2023-02, with the labels that each got.

#239 CLI support for callable class instances
  CHANGELOG.rst
  jsonargparse/cli.py
  jsonargparse/typehints.py
  jsonargparse_tests/base.py
  jsonargparse_tests/test_cli.py
Labels: enhancement

#242 Fix `fail_untyped` for Dataclasses
  CHANGELOG.rst
  jsonargparse/signatures.py
  jsonargparse_tests/test_signatures.py
Labels: enhancement

#240 Improved error messages when fail_untyped=True
  CHANGELOG.rst
  jsonargparse/signatures.py
  jsonargparse_tests/test_signatures.py
Labels: refactor

#246 Fix dump not working for partial callable return instance
  CHANGELOG.rst
  jsonargparse/typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug
