Repository omni-us/jsonargparse, pull requests merged in 2023-06, with the labels that each got.

#290 Fix failures for nested argument in optional dataclass type
  CHANGELOG.rst
  jsonargparse/typehints.py
  jsonargparse_tests/test_dataclass_like.py
Labels: bug

#293 Refactor core and deprecated tests using pytest
  jsonargparse_tests/base.py
  jsonargparse_tests/conftest.py
  jsonargparse_tests/test_actions.py
  jsonargparse_tests/test_cli.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_dataclass_like.py
  jsonargparse_tests/test_deprecated.py
  jsonargparse_tests/test_link_arguments.py
  jsonargparse_tests/test_loaders_dumpers.py
  jsonargparse_tests/test_namespace.py
  jsonargparse_tests/test_optionals.py
  jsonargparse_tests/test_paths.py
  jsonargparse_tests/test_signatures.py
  jsonargparse_tests/test_stubs_resolver.py
  jsonargparse_tests/test_subclasses.py
  jsonargparse_tests/test_subcommands.py
  jsonargparse_tests/test_typehints.py
  jsonargparse_tests/test_typing.py
  jsonargparse_tests/test_util.py
Labels: refactor

#295 Fix lazy_instance regression introduced in 540f91f
  jsonargparse/typehints.py
Labels: bug, refactor

#296 Fix argument links applied on parse silently ignored when the source validation fails
  CHANGELOG.rst
  jsonargparse/link_arguments.py
  jsonargparse_tests/test_link_arguments.py
Labels: bug

#303 Fix attrs fields with factory default causes parse to fail
  CHANGELOG.rst
  jsonargparse/parameter_resolvers.py
  jsonargparse_tests/test_dataclass_like.py
Labels: bug

#305 Rename default branch to main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/code-checks.yml
  .github/workflows/codeql.yml
  .github/workflows/tests.yml
  README.rst
Labels: refactor

#306 ruff: isort
  .pre-commit-config.yaml
  jsonargparse/actions.py
  pyproject.toml
Labels: refactor

#304 stop subclass dive if you hit bad import
  CHANGELOG.rst
  jsonargparse/typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug

#298 Parameters that receive a path also accept os.PathLike type
  CHANGELOG.rst
  jsonargparse/core.py
  jsonargparse/util.py
  jsonargparse_tests/test_actions.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_formatters.py
  jsonargparse_tests/test_jsonnet.py
  jsonargparse_tests/test_jsonschema.py
  jsonargparse_tests/test_optionals.py
  jsonargparse_tests/test_paths.py
  jsonargparse_tests/test_signatures.py
  jsonargparse_tests/test_subclasses.py
  jsonargparse_tests/test_typehints.py
  jsonargparse_tests/test_util.py
Labels: enhancement

#308 Few minor changes
  .pre-commit-config.yaml
  jsonargparse/link_arguments.py
  jsonargparse/signatures.py
  jsonargparse_tests/test_typehints.py
Labels: refactor

#307 class_from_function now supports func_return parameter
  CHANGELOG.rst
  jsonargparse/util.py
  jsonargparse_tests/test_util.py
Labels: enhancement

#302 Added _ prefix to module names to be explicit about non-public API
  .pre-commit-config.yaml
  CHANGELOG.rst
  jsonargparse/__init__.py
  jsonargparse/_actions.py
  jsonargparse/_cli.py
  jsonargparse/_common.py
  jsonargparse/_core.py
  jsonargparse/_deprecated.py
  jsonargparse/_formatters.py
  jsonargparse/_jsonnet.py
  jsonargparse/_jsonschema.py
  jsonargparse/_link_arguments.py
  jsonargparse/_loaders_dumpers.py
  jsonargparse/_namespace.py
  jsonargparse/_optionals.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse/_stubs_resolver.py
  jsonargparse/_type_checking.py
  jsonargparse/_typehints.py
  jsonargparse/_util.py
  jsonargparse/typing.py
  jsonargparse_tests/__init__.py
  jsonargparse_tests/conftest.py
  jsonargparse_tests/test_cli.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_dataclass_like.py
  jsonargparse_tests/test_deprecated.py
  jsonargparse_tests/test_jsonnet.py
  jsonargparse_tests/test_loaders_dumpers.py
  jsonargparse_tests/test_namespace.py
  jsonargparse_tests/test_optionals.py
  jsonargparse_tests/test_parameter_resolvers.py
  jsonargparse_tests/test_signatures.py
  jsonargparse_tests/test_stubs_resolver.py
  jsonargparse_tests/test_typehints.py
  jsonargparse_tests/test_util.py
Labels: refactor

#294 Add support for PEP 563, 585 and 604 for python>=3.7
  .circleci/config.yml
  .pre-commit-config.yaml
  CHANGELOG.rst
  README.rst
  jsonargparse/_backports.py
  jsonargparse/_link_arguments.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse/_stubs_resolver.py
  jsonargparse/_util.py
  jsonargparse_tests/conftest.py
  jsonargparse_tests/test_actions.py
  jsonargparse_tests/test_argcomplete.py
  jsonargparse_tests/test_backports.py
  jsonargparse_tests/test_cli.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_dataclass_like.py
  jsonargparse_tests/test_deprecated.py
  jsonargparse_tests/test_formatters.py
  jsonargparse_tests/test_jsonnet.py
  jsonargparse_tests/test_jsonschema.py
  jsonargparse_tests/test_link_arguments.py
  jsonargparse_tests/test_loaders_dumpers.py
  jsonargparse_tests/test_namespace.py
  jsonargparse_tests/test_optionals.py
  jsonargparse_tests/test_parameter_resolvers.py
  jsonargparse_tests/test_paths.py
  jsonargparse_tests/test_signatures.py
  jsonargparse_tests/test_stubs_resolver.py
  jsonargparse_tests/test_subclasses.py
  jsonargparse_tests/test_subcommands.py
  jsonargparse_tests/test_typehints.py
  jsonargparse_tests/test_typing.py
  jsonargparse_tests/test_util.py
  pyproject.toml
Labels: enhancement

#310 Add support for range as a type
  CHANGELOG.rst
  README.rst
  jsonargparse/typing.py
  jsonargparse_tests/test_typing.py
Labels: enhancement

#313 Fix parameter without default and type optional incorrectly added as a required argument
  CHANGELOG.rst
  jsonargparse/_signatures.py
  jsonargparse/_typehints.py
  jsonargparse_tests/test_dataclass_like.py
Labels: bug

#314 Fix class_from_function not failing when return annotation is missing
  CHANGELOG.rst
  jsonargparse/_util.py
  jsonargparse_tests/test_parameter_resolvers.py
  jsonargparse_tests/test_util.py
Labels: bug
