Repository omni-us/jsonargparse, pull requests merged in 2023-07, with the labels that each got.

#319 Fix help print for parsers that have a link target lacking type and help
  CHANGELOG.rst
  jsonargparse/_link_arguments.py
  jsonargparse_tests/test_link_arguments.py
Labels: bug

#320 Switch test coverage to use pytest-cov
  .circleci/config.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  jsonargparse_tests/__main__.py
  pyproject.toml
  setup.py
Labels: refactor

#321 Removing unused project configuration
  .gitignore
  jsonargparse_tests/__main__.py
  pyproject.toml
Labels: refactor

#323 Fix invalid environment variable names when env_prefix is derived from a prog containing dashes
  CHANGELOG.rst
  jsonargparse/_formatters.py
  jsonargparse_tests/test_core.py
Labels: bug

#327 Fix inconsistent ARG and missing ENV in help when default_env=True
  CHANGELOG.rst
  jsonargparse/_formatters.py
  jsonargparse_tests/test_formatters.py
  jsonargparse_tests/test_signatures.py
  jsonargparse_tests/test_subclasses.py
Labels: bug

#328 Fix Literal types on python 3.9 when typing_extensions is installed
  CHANGELOG.rst
  jsonargparse/_typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug

#324 Subcommands main parser help changes
  CHANGELOG.rst
  jsonargparse/_actions.py
  jsonargparse/_formatters.py
  jsonargparse_tests/test_subcommands.py
Labels: enhancement

#315 Valid import path for classes created with class_from_function
  CHANGELOG.rst
  README.rst
  jsonargparse/_util.py
  jsonargparse_tests/test_util.py
Labels: enhancement

#329 readme: fix link to docs
  README.rst
Labels: documentation

#331 Switch away from setup.py to build package
  .circleci/config.yml
  .pre-commit-config.yaml
  README.rst
  pyproject.toml
Labels: refactor

#333 Fix save failure when a link target is a required parameter nested in a subclass
  CHANGELOG.rst
  jsonargparse/_typehints.py
  jsonargparse_tests/test_link_arguments.py
Labels: bug
