Repository omni-us/jsonargparse, pull requests merged in 2023-09, with the labels that each got.

#369 Fix ActionJsonSchema not setting correctly defaults when schema uses oneOf
  CHANGELOG.rst
  jsonargparse/_jsonschema.py
  jsonargparse_tests/test_jsonschema.py
Labels: bug

#370 Fix recommended print_config steps failure when default_config_files is used
  CHANGELOG.rst
  jsonargparse/_core.py
  jsonargparse_tests/test_core.py
Labels: bug

#371 better error message when subcommand is not given
  CHANGELOG.rst
  jsonargparse/_actions.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_subcommands.py
Labels: refactor

#373 Remove support for python 3.6
  .circleci/config.yml
  .pre-commit-config.yaml
  .sonarcloud.properties
  CHANGELOG.rst
  jsonargparse/__init__.py
  jsonargparse/_deprecated.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_postponed_annotations.py
  jsonargparse/_typehints.py
  jsonargparse/_util.py
  jsonargparse_tests/test_core.py
  jsonargparse_tests/test_dataclass_like.py
  jsonargparse_tests/test_deprecated.py
  jsonargparse_tests/test_signatures.py
  pyproject.toml
Labels: refactor

#381 Better error message when link compute_fn fails
  CHANGELOG.rst
  jsonargparse/_actions.py
  jsonargparse/_link_arguments.py
  jsonargparse_tests/test_link_arguments.py
Labels: bug, enhancement

#382 Add typos to pre-commit config
  .pre-commit-config.yaml
  pyproject.toml
Labels: refactor

#386 Fix postponed annotations not working for dataclasses
  CHANGELOG.rst
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_postponed_annotations.py
  jsonargparse_tests/test_postponed_annotations.py
Labels: bug

#378 Add support for user-defined generic types
  CHANGELOG.rst
  DOCUMENTATION.rst
  README.rst
  jsonargparse/_common.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse/_util.py
  jsonargparse_tests/test_dataclass_like.py
  jsonargparse_tests/test_signatures.py
Labels: enhancement

#376 Add support for python 3.12
  .github/workflows/tests.yml
  .sonarcloud.properties
  CHANGELOG.rst
  jsonargparse_tests/test_stubs_resolver.py
  jsonargparse_tests/test_subclasses.py
  pyproject.toml
Labels: enhancement

#380 Creation of custom types
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/typing.py
  jsonargparse_tests/test_typing.py
Labels: enhancement, documentation

#383 fix `parse_args` for `Callable` with multiple input arguments
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/_typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug

#389 Add support for Annotated types and fix for pydantic v2
  .circleci/config.yml
  .pre-commit-config.yaml
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/_common.py
  jsonargparse/_optionals.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse/_typehints.py
  jsonargparse/typing.py
  jsonargparse_tests/test_dataclass_like.py
  pyproject.toml
Labels: bug, enhancement

#390 Fix unsupported pop/get default incorrectly sets default as None
  CHANGELOG.rst
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse_tests/test_link_arguments.py
  jsonargparse_tests/test_parameter_resolvers.py
Labels: bug
