Repository omni-us/jsonargparse, pull requests merged in 2024-04, with the labels that each got.

#475 Feature path std io
  CHANGELOG.rst
  jsonargparse/_typehints.py
  jsonargparse/_util.py
  jsonargparse_tests/test_util.py
Labels: enhancement

#486 Account for breaking change in argparse.ArgumentParser._parse_optional affecting python 3.11.9 and likely >=3.13
  CHANGELOG.rst
  jsonargparse/_core.py
  jsonargparse/_typehints.py
  jsonargparse_tests/test_argcomplete.py
Labels: bug

#485 New option in CLI to provide subcommands help when components given in a dict
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/_cli.py
  jsonargparse_tests/test_cli.py
Labels: enhancement

#488 Disable argcomplete tests also in python >= 3.12.3 and update pre-commit config
  .pre-commit-config.yaml
  jsonargparse_tests/test_argcomplete.py
Labels: refactor

#487 Fix lazy_instance not working for callable classes
  CHANGELOG.rst
  jsonargparse/_typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug

#489 Fix argcomplete compatibility
  .circleci/config.yml
  CHANGELOG.rst
  jsonargparse_tests/test_argcomplete.py
  pyproject.toml
Labels: bug

#483 Callable type with class return and zero arguments not working
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/_typehints.py
  jsonargparse_tests/test_typehints.py
Labels: bug

#480 Fixes for non-stdlib dataclass-like types
  CHANGELOG.rst
  DOCUMENTATION.rst
  jsonargparse/_common.py
  jsonargparse/_optionals.py
  jsonargparse/_parameter_resolvers.py
  jsonargparse/_signatures.py
  jsonargparse/_typehints.py
  jsonargparse_tests/test_dataclass_like.py
Labels: bug, enhancement

#490 Pending changes from pull request #475
  CHANGELOG.rst
  jsonargparse/_typehints.py
  jsonargparse/_util.py
  jsonargparse/typing.py
  jsonargparse_tests/conftest.py
  jsonargparse_tests/test_paths.py
Labels: bug

#492 Update versions of github actions that are deprecated
  .github/workflows/codeql.yml
  .github/workflows/tests.yml
Labels: refactor

#493 Split circleci tests to ease reading of logs
  .circleci/config.yml
Labels: refactor
